# Generated by Django 2.1.7 on 2019-08-24 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.SmallIntegerField(verbose_name='participant1 drawn number')),
                ('id2', models.SmallIntegerField(verbose_name='participant2 drawn number')),
                ('game_date', models.DateField(blank=True, null=True, verbose_name='game date')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='game start time')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawn_number', models.SmallIntegerField(blank=True, null=True, verbose_name='drawn number')),
                ('win_sets', models.IntegerField(default=0)),
                ('win_balls', models.IntegerField(default=0)),
                ('games_left', models.IntegerField(default=10)),
                ('initialized', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SetResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.SmallIntegerField(verbose_name='set number')),
                ('result1', models.SmallIntegerField(verbose_name='participant1 result')),
                ('result2', models.SmallIntegerField(verbose_name='participant2 result')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', verbose_name='description')),
                ('single', models.BooleanField(default=True, verbose_name='if the tournament is single')),
                ('reg_end', models.DateTimeField(verbose_name='registration end time')),
                ('draw_time', models.DateTimeField(verbose_name='draw time')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('start_date_playoff', models.DateField(verbose_name='start date of play-off')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('games_per_person', models.SmallIntegerField(default=10, verbose_name='number of games for each participant during the group stage')),
                ('number_of_sets', models.SmallIntegerField(default=5, verbose_name='number of sets in one game of the group stage')),
                ('game_start_time', models.TimeField(default='11:00:00', verbose_name='games start time')),
                ('game_duration', models.DurationField(default='00:30:00', verbose_name='games duration')),
                ('participants', models.ManyToManyField(through='tournament.Participant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament'),
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='game',
            name='participant1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='participant1', to='tournament.Participant'),
        ),
        migrations.AddField(
            model_name='game',
            name='participant2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='participant2', to='tournament.Participant'),
        ),
        migrations.AddField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament'),
        ),
    ]
