# Generated by Django 2.1.7 on 2019-08-24 18:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0003_auto_20190824_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='participants',
            field=models.ManyToManyField(through='tournament.Participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
