# Generated by Django 2.1.7 on 2019-08-24 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_tournament_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='participant1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='participant1', to='tournament.Participant'),
        ),
        migrations.AddField(
            model_name='game',
            name='participant2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='participant2', to='tournament.Participant'),
        ),
    ]
