# Generated by Django 2.1.7 on 2019-08-26 19:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0005_auto_20190824_2341'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('tournament', 'user')},
        ),
    ]
