# Generated by Django 2.1.7 on 2019-08-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_auto_20190827_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='debug',
            field=models.BooleanField(default=False, verbose_name='if debug mode'),
        ),
    ]
